[basicnetworking]
label = "Basic networking"

    [[basicnetworking.questions]]
    question = "A connecting of computers and local networks located at a remote distance to share worldwide information resources is called"
    answers = ["global network"]
    alternatives = ["corporate network", "regional network", "local network"]

    [[basicnetworking.questions]]
    question = "What does network topology defines"
    answers = [
        "A description of the network configuration, diagram\n     and connection of network devices.",
    ]
    alternatives = [
        "Diagram of location of computers in the network.", 
        "Scheme of interaction of switching equipment.", 
        "Network security technology.",
    ]

    [[basicnetworking.questions]]
    question = "Which of the following are types of network topology"
    answers = ["Bus, ring, star"]
    alternatives = ["Straight, parallel, cross", "Topological, logical, mixed", "Vector, singularity, parallelism"]

    [[basicnetworking.questions]]
    question = "What the effectiveness of computer communication usually depends on"
    answers = ["All choices"]
    alternatives = ["Channel thruput", "Amount of the computer's RAM", "Processor productivity"]

    [[basicnetworking.questions]]
    question = "What makes it impossible to connect a computer to a local network"
    answers = ["Lack of network adapter"]
    alternatives = ["Channel thruput", "Limited hard disk size", "No serial port"]

    [[basicnetworking.questions]]
    question = "The following transmission media are usually used in computer networks"
    answers = ["All choices"]
    alternatives = ["Radio", "Twisted pair", "Optical fiber"]

    [[basicnetworking.questions]]
    question = "What is the advantage of using a mesh topology"
    answers = ["High reliability and fault tolerance"]
    alternatives = ["Minimum number of connections", "Simple network scaling", "Low cost"]

    [[basicnetworking.questions]]
    question = "What topology is the basis of the global Internet"
    answers = ["Mesh"]
    alternatives = ["Star", "Tree", "Ring"]

    [[basicnetworking.questions]]
    question = "A MAC address is"
    answers = ["the physical address of the network interface"]
    alternatives = [
        "physical address of the computer",
        "logical address of the computer",
        "the logical address to which all packets on the network are sent",
    ]

    [[basicnetworking.questions]]
    question = "What type of address directly ensures the delivery of frames between computers within a shared local network"
    answers = ["MAC address"]
    alternatives = ["IP address", "Domain name", "NetBIOS name"]

    [[basicnetworking.questions]]
    question = "How many bits are the length of a MAC address"
    answers = ["48"]
    alternatives = ["32", "128", "64"]

    [[basicnetworking.questions]]
    question = "A MAC address is associated with which layer of the OSI model"
    answers = ["data-link"]
    alternatives = ["physical", "network", "transport"]

    [[basicnetworking.questions]]
    question = "An IP address is associated with which layer of the OSI model"
    answers = ["network"]
    alternatives = ["physical", "data-link", "transport"]   

    [[basicnetworking.questions]]
    question = "What type of address directly ensures the delivery of packets between computers on the global Internet"
    answers = ["IP address"]
    alternatives = ["MAC address", "WEB address", "TCP address"]    
    
    [[basicnetworking.questions]]
    question = "The prefix in the IP address indicates"
    answers = ["the number of leading ones in the subnet mask"]
    alternatives = [
        "the number of leading zeros in the subnet mask",
        "the maximum number of computers in the subnet",
        "the maximum number of subnets",
    ]    
    
    [[basicnetworking.questions]]
    question = "What are the parts of an IP address in IPv4"
    answers = ["network ID", "host ID"]
    alternatives = ["manufacturer ID of the network adapter", "The IP address is not structured"]        
    
    [[basicnetworking.questions]]
    question = "The number of bytes in an IPv4 address"
    answers = ["4"]
    alternatives = ["32", "8", "64"]     
    
    [[basicnetworking.questions]]
    question = "How is an IPv6 address displayed"
    answers = ["as hexadecimal numbers separated by ':'"]
    alternatives = [
        "as decimal numbers separated by dots",
        "as binary numbers separated by ':'",
        "as binary-decimal numbers separated by '-'",
    ]
 
    [[basicnetworking.questions]]
    question = "Which are the correct compact presentation forms for an IPv6\naddress FE80:0000:0000:0100:0000:0000:0000:0123"
    answers = ["FE80:0:0:100::123", "FE80:0:0:100:0:0:0:123"]
    alternatives = [
        "FE80::100::123",
        "FE80::1:0000:0000:0000:123",
    ] 
 
    [[basicnetworking.questions]]
    question = "What is a network prefix"
    answers = [
        "decimal number equal to the number of bits\n     of the subnet mask set to one",
    ]
    alternatives = [
        "a hexadecimal number equal to the number of bits\n     of the subnet mask set to one", 
        "a decimal number equal to the number of bits\n     of the subnet mask set to zero", 
        "the first octet of the IP address",
    ] 
 
    [[basicnetworking.questions]]
    question = "Which addresses in any IPv4 network are always reserved?"
    answers = ["network address", "broadcast address for this network"]
    alternatives = [
        "first available address for default gateway",
        "last available address for default gateway",
        "each odd address for better balancing",
    ] 
    hint = "In IPv4 there are two IPs that cannot be assigned to any devices."
    explanation = """
    Each network or subnet has a reserved broadcast address 
    that can be used by all participants of the network to 
    send a broadcast. Broadcasts allow information and services 
    to be transmitted to all devices and components of the 
    network without the need to know their individual IP 
    addresses. 
        
    Among other things, routers in a local area network use 
    the broadcast IP to send HELLO packets to all endpoints, 
    switches, and other routers to maintain interrelationships 
    on the network and discover neighboring devices. These are 
    the Network ID and the Broadcast IP address.
    """

    [[basicnetworking.questions]]
    question = "What decimal number is equivalent to a binary number 11111111"
    answers = ["255"]
    alternatives = ["16", "8", "64"]  
    
    [[basicnetworking.questions]]
    question = "Which of the following address ranges are private"
    answers = ["172.16.0.0/12", "10.0.0.0/8", "192.168.0.0/16"]
    alternatives = [
        "1.1.1.0/30", 
        "127.0.0.0/24", 
        "169.254.0.0/16", 
        "193.168.255.0/24",
    ]
    hint = "There are three private address ranges."
    explanation = """
    Address ranges to be used by private networks are:
        
    Class A: 10.0.0.0 to 10.255.255.255
    Class B: 172.16.0.0 to 172.31.255.255
    Class C: 192.168.0.0 to 192.168.255.255
    """
    
    [[basicnetworking.questions]]
    question = "How is the boundary between the network and host portions of an IPv4 address defined in modern networks"
    answers = ["using the network prefix", "using the subnet mask"]
    alternatives = ["using classes", "the border is fixed and unchanging"]  

    [[basicnetworking.questions]]
    question = "What is the advantage of using a router in a local network"
    answers = ["All choices"]
    alternatives = ["Logical structuring of the network", "Improving network security", "Broadcast traffic filtering"]  

    [[basicnetworking.questions]]
    question = "Why do you need a default gateway"
    answers = ["All packets addressed outside the subnet\n     are sent to this IP address"]
    alternatives = [
        "All packets sent to this IP address are bounced back",
        "A host with this IP address matches the domain\n     name and IP address",
        "From this IP address, the computer receives the IP address,\n     subnet mask, and DNS server settings",
    ] 

    [[basicnetworking.questions]]
    question = "There are 2 rules in the routing table: 1. 10.0.0.0 255.255.255.0 10.0.0.1\nand 2. 10.0.0.0 255.255.255.240 10.0.0.2. Packets for recipient 10.0.0.8\nwill be sent to the gateway"
    answers = ["10.0.0.2"]
    alternatives = ["10.0.0.1", "10.0.0.0", "255.255.255.0", "255.255.255.240"] 

[networkprotocols]
label = "Network Protocols"

    [[networkprotocols.questions]]
    question = "A broadcast address at the data-link layer is: "
    answers = ["FF:FF:FF:FF:FF:FF"]
    alternatives = ["255.255.255.255", "00:00:00:00:00:00", "0.0.0.0"]  

    [[networkprotocols.questions]]
    question = "Choose the correct statement: "
    answers = ["The ARP protocol is designed to determine the MAC address\n     based on the IP address"]
    alternatives = [
        "ARP is running on port 53", 
        "ARP is used in both IPv4 and IPv6 networks", 
        "ARP protocol is designed to determine the IP address\n     based on the MAC address",
    ] 
    hint = "ARP works between Layers 2 and 3 of the OSI model."
    explanation = """
    Address Resolution Protocol (ARP) is a procedure for mapping a dynamic
    IP address to a permanent physical machine address in a local area 
    network (LAN). The physical machine address is also known as a media 
    access control (MAC) address.
    """

    [[networkprotocols.questions]]
    question = "The TCP protocol is: "
    answers = ["reliable", "connection orientated"]
    alternatives = ["lightweight", "correct", "faster then UDP"]  

    [[networkprotocols.questions]]
    question = "The sliding window mechanism in TCP is used for: "
    answers = ["better utilization of network bandwidth"]
    alternatives = [
        "increasing the reliability of data delivery", 
        "establishing a connection between the client and the server", 
        "increasing the size of the data segment being transmitted",
    ] 

    [[networkprotocols.questions]]
    question = "The set SYN flag indicates that: "
    answers = ["the client and server go through the 'handshake' phase,\n     establishing the connection"]
    alternatives = [
        "the server waits for the data segment with the number of the first\n     byte specified in the Sequence number field", 
        "the server waits for the data segment with the number of the first\n     byte specified in the Acknowledgment number field", 
        "the client and server are ready to transmit data segments",
    ] 
    hint = "SYN (synchronize): Packets that are used to initiate a connection."
    explanation = """
    SYN - The synchronisation flag is used as a first step in establishing 
    a three way handshake between two hosts. Only the first packet from both
    the sender and receiver should have this flag set. The following diagram
    illustrates a three way handshake process.  
    """
    
    [[networkprotocols.questions]]
    question = "The UDP protocol is: "
    answers = ["lightweight", "faster then TCP"]
    alternatives = ["connection orientated", "correct"]  

    [[networkprotocols.questions]]
    question = "The UDP pseudo-header is used for: "
    answers = ["checksum calculation"]
    alternatives = ["formation of the IP header", "improvement of delivery reliability", "All choices"]  

    [[networkprotocols.questions]]
    question = "Choose the correct statements: "
    answers = ["UDP transfers data faster than TCP", "UDP is used in streaming services and online games"]
    alternatives = ["Minimum UDP header length is 6 bytes", "The checksum in UDP is mandatary"] 

    [[networkprotocols.questions]]
    question = "Choose the correct statements: "
    answers = [
        "Ping and traceroute use ICMP protocol", 
        "If the recipient is out of network, the client will receive\n     a Destination unreachable message",
    ]
    alternatives = [
        "If the ICMP message is lost, it is retransmitted", 
        "ICMP is used to control the data rate on the network",
    ] 

    [[networkprotocols.questions]]
    question = "Choose the correct statements: "
    answers = [
        "HTTP protocol runs on port 80 over TCP protocol", 
        "Registered ports are assigned by IANA for specific service\n     upon application by a requesting entity",
    ]
    alternatives = [
        "The total number of TCP ports is 1024", 
        "Ephemeral ports used by system processes that provide\n     widely used types of network services",
    ] 

    [[networkprotocols.questions]]
    question = "How is an IPv6 address displayed"
    answers = ["as hexadecimal numbers separated by ':'"]
    alternatives = [
        "as decimal numbers separated by dots",
        "as binary numbers separated by ':'",
        "as binary-decimal numbers separated by '-'",
    ]

[subnetting]
label = "Concept of Subnetting"

    [[subnetting.questions]]
    question = "What is the largest in capacity classful network"
    answers = ["A"]
    alternatives = ["B", "C", "D"] 

    [[subnetting.questions]]
    question = "The network class is determined by: "
    answers = ["The first bits of the first byte of the IP address"]
    alternatives = [
        "Network mask/prefix", 
        "The first bits of the last byte of the IP address", 
        "Internet Services Provider",
    ] 

[gogi]
label = "Gogi"
[gogi.mogi]
label = "Gogi Mogi"
    [[gogi.mogi.questions]]
    question = "The network class is determined by: "
    answers = ["The first bits of the first byte of the IP address"]
    alternatives = [
        "Network mask/prefix", 
        "The first bits of the last byte of the IP address", 
        "Internet Services Provider",
    ] 

[python]
label = "Python"

    [[python.questions]]
    question     = "When was the first known use of the word 'quiz'"
    answers      = ["1781"]
    alternatives = ["1771", "1871", "1881"]

    [[python.questions]]
    question     = "Which built-in function can get information from the user"
    answers      = ["input"]
    alternatives = ["get", "print", "write"]

    [[python.questions]]
    question = "What's the purpose of the built-in zip() function"
    answers = ["To iterate over two or more sequences at the same time"]
    alternatives = [
        "To combine several strings into one",
        "To compress several files into one archive",
        "To get information from the user",
    ]

    [[python.questions]]
    question     = "What does dict.get(key) return if key isn't found in dict"
    answers      = ["None"]
    alternatives = ["key", "True", "False"]

    [[python.questions]]
    question = "How do you iterate over both the indices and elements in an iterable"
    answers = ["enumerate(iterable)"]
    alternatives = [
        "enumerate(iterable, start=1)",
        "range(iterable)",
        "range(iterable, start=1)",
    ]

    [[python.questions]]
    question = "What's the official name of the := operator"
    answers = ["Assignment expression"]
    alternatives = [
        "Named expression",
        "Walrus operator",
        "Colon equals operator",
    ]

    [[python.questions]]
    question = "What's one effect of calling random.seed(42)"
    answers = ["The random numbers are reproducible."]
    alternatives = [
        "The random numbers are more random.",
        "The computer clock is reset.",
        "The first random number is always 42.",
    ]

    [[python.questions]]
    question     = "Which version of Python is the first with TOML support built in"
    answers      = ["3.11"]
    alternatives = ["3.9", "3.10", "3.12"]

    [[python.questions]]
    question     = "How can you run a Python script named quiz.py"
    answers      = ["python quiz.py", "python -m quiz"]
    alternatives = ["python quiz", "python -m quiz.py"]
    hint         = "One option uses the filename, and the other uses the module name."

    [[python.questions]]
    question     = "What's the name of the list-like data structure in TOML"
    answers      = ["Array"]
    alternatives = ["List", "Sequence", "Set"]

    [[python.questions]]
    question = "What's a PEP"
    answers = ["A Python Enhancement Proposal"]
    alternatives = [
        "A Pretty Exciting Policy",
        "A Preciously Evolved Python",
        "A Potentially Epic Prize",
    ]
    hint = "PEPs are used to evolve Python."
    explanation = """
    Python Enhancement Proposals (PEPs) are design documents that provide
    information to the Python community. PEPs are used to propose new features
    for the Python language, to collect community input on an issue, and to
    document design decisions made about the language.
    """

    [[python.questions]]
    question = "How can you add a docstring to a function"
    answers = [
        "By writing a string literal as the first statement in the function",
        "By assigning a string to the function's .__doc__ attribute",
    ]
    alternatives = [
        "By using the built-in @docstring decorator",
        "By returning a string from the function",
    ]
    hint = "They are parsed from your code and stored on the function object."
    explanation = """
    Docstrings document functions and other Python objects. A docstring is a
    string literal that occurs as the first statement in a module, function,
    class, or method definition. Such a docstring becomes the .__doc__ special
    attribute of that object. See PEP 257 for more information.
    There's no built-in @docstring decorator. Many functions naturally return
    strings. Such a feature can therefore not be used for docstrings.
    """

    [[python.questions]]
    question = "When was the first public version of Python released"
    answers = ["February 1991"]
    alternatives = ["January 1994", "October 2000", "December 2008"]
    hint = "The first public version was labeled version 0.9.0."
    explanation = """
    Guido van Rossum started work on Python in December 1989. He posted
    Python v0.9.0 to the alt.sources newsgroup in February 1991. Python
    reached version 1.0.0 in January 1994. The next major versions,
    Python 2.0 and Python 3.0, were released in October 2000 and December
    2008, respectively.
    """
