[basicnetworking]
label = "Basic networking"

    [[basicnetworking.questions]]
    question = "A connecting of computers and local networks located at a remote distance to share worldwide information resources is called"
    answers = ["global network"]
    alternatives = ["corporate network", "regional network", "local network"]

    [[basicnetworking.questions]]
    question = "What does network topology defines"
    answers = [
        "A description of the network configuration, diagram\n     and connection of network devices.",
    ]
    alternatives = [
        "Diagram of location of computers in the network.", 
        "Scheme of interaction of switching equipment.", 
        "Network security technology.",
    ]

    [[basicnetworking.questions]]
    question = "Which of the following are types of network topology"
    answers = ["Bus, ring, star"]
    alternatives = ["Straight, parallel, cross", "Topological, logical, mixed", "Vector, singularity, parallelism"]

    [[basicnetworking.questions]]
    question = "What the effectiveness of computer communication usually depends on"
    answers = ["All choices"]
    alternatives = ["Channel thruput", "Amount of the computer's RAM", "Processor productivity"]

    [[basicnetworking.questions]]
    question = "What makes it impossible to connect a computer to a local network"
    answers = ["Lack of network adapter"]
    alternatives = ["Channel thruput", "Limited hard disk size", "No serial port"]

    [[basicnetworking.questions]]
    question = "The following transmission media are usually used in computer networks"
    answers = ["All choices"]
    alternatives = ["Radio", "Twisted pair", "Optical fiber"]

    [[basicnetworking.questions]]
    question = "What is the advantage of using a mesh topology"
    answers = ["High reliability and fault tolerance"]
    alternatives = ["Minimum number of connections", "Simple network scaling", "Low cost"]

    [[basicnetworking.questions]]
    question = "What topology is the basis of the global Internet"
    answers = ["Mesh"]
    alternatives = ["Star", "Tree", "Ring"]

    [[basicnetworking.questions]]
    question = "A MAC address is"
    answers = ["the physical address of the network interface"]
    alternatives = [
        "physical address of the computer",
        "logical address of the computer",
        "the logical address to which all packets on the network are sent",
    ]

    [[basicnetworking.questions]]
    question = "What type of address directly ensures the delivery of frames between computers within a shared local network"
    answers = ["MAC address"]
    alternatives = ["IP address", "Domain name", "NetBIOS name"]

    [[basicnetworking.questions]]
    question = "How many bits are the length of a MAC address"
    answers = ["48"]
    alternatives = ["32", "128", "64"]

    [[basicnetworking.questions]]
    question = "A MAC address is associated with which layer of the OSI model"
    answers = ["data-link"]
    alternatives = ["physical", "network", "transport"]

    [[basicnetworking.questions]]
    question = "An IP address is associated with which layer of the OSI model"
    answers = ["network"]
    alternatives = ["physical", "data-link", "transport"]   

    [[basicnetworking.questions]]
    question = "What type of address directly ensures the delivery of packets between computers on the global Internet"
    answers = ["IP address"]
    alternatives = ["MAC address", "WEB address", "TCP address"]    
    
    [[basicnetworking.questions]]
    question = "The prefix in the IP address indicates"
    answers = ["the number of leading ones in the subnet mask"]
    alternatives = [
        "the number of leading zeros in the subnet mask",
        "the maximum number of computers in the subnet",
        "the maximum number of subnets",
    ]    
    
    [[basicnetworking.questions]]
    question = "What are the parts of an IP address in IPv4"
    answers = ["network ID", "host ID"]
    alternatives = ["manufacturer ID of the network adapter", "The IP address is not structured"]        
    
    
    
    
    
    [[basicnetworking.questions]]
    question = "Which of the following address ranges are private"
    answers = ["172.16.0.0/12", "10.0.0.0/8", "192.168.0.0/16"]
    alternatives = [
        "1.1.1.0/30", 
        "127.0.0.0/24", 
        "169.254.0.0/16", 
        "193.168.255.0/24",
    ]
    hint = "There are three private address ranges."
    explanation = """
        Address ranges to be used by private networks are:
        
        Class A: 10.0.0.0 to 10.255.255.255
        Class B: 172.16.0.0 to 172.31.255.255
        Class C: 192.168.0.0 to 192.168.255.255
    """

[capitals]
label = "Capitals"

    [[capitals.questions]]
    question = "What's the capital of Norway"
    answers = ["Oslo"]
    hint = "Lars Onsager, Jens Stoltenberg, Trygve Lie, and Børge Ousland."
    alternatives = ["Stockholm", "Copenhagen", "Helsinki", "Reykjavik"]
    explanation = """
    Oslo was founded as a city in the 11th century and established as a
    trading place. It became the capital of Norway in 1299. The city was
    destroyed by a fire in 1624 and rebuilt as Christiania, named in honor
    of the reigning king. The city was renamed back to Oslo in 1925.
    """

    [[capitals.questions]]
    question = "What's the state capital of Texas, USA"
    answers = ["Austin"]
    alternatives = ["Harrisburg", "Houston", "Galveston", "Columbia"]
    hint = "SciPy is held there each year."
    explanation = """
    Austin is named in honor of Stephen F. Austin. It was purpose-built to
    be the capital of Texas and was incorporated in December 1839. Houston,
    Harrisburg, Columbia, and Galveston are all earlier capitals of Texas.
    """

[python]
label = "Python"

    [[python.questions]]
    question     = "When was the first known use of the word 'quiz'"
    answers      = ["1781"]
    alternatives = ["1771", "1871", "1881"]

    [[python.questions]]
    question     = "Which built-in function can get information from the user"
    answers      = ["input"]
    alternatives = ["get", "print", "write"]

    [[python.questions]]
    question = "What's the purpose of the built-in zip() function"
    answers = ["To iterate over two or more sequences at the same time"]
    alternatives = [
        "To combine several strings into one",
        "To compress several files into one archive",
        "To get information from the user",
    ]

    [[python.questions]]
    question     = "What does dict.get(key) return if key isn't found in dict"
    answers      = ["None"]
    alternatives = ["key", "True", "False"]

    [[python.questions]]
    question = "How do you iterate over both the indices and elements in an iterable"
    answers = ["enumerate(iterable)"]
    alternatives = [
        "enumerate(iterable, start=1)",
        "range(iterable)",
        "range(iterable, start=1)",
    ]

    [[python.questions]]
    question = "What's the official name of the := operator"
    answers = ["Assignment expression"]
    alternatives = [
        "Named expression",
        "Walrus operator",
        "Colon equals operator",
    ]

    [[python.questions]]
    question = "What's one effect of calling random.seed(42)"
    answers = ["The random numbers are reproducible."]
    alternatives = [
        "The random numbers are more random.",
        "The computer clock is reset.",
        "The first random number is always 42.",
    ]

    [[python.questions]]
    question     = "Which version of Python is the first with TOML support built in"
    answers      = ["3.11"]
    alternatives = ["3.9", "3.10", "3.12"]

    [[python.questions]]
    question     = "How can you run a Python script named quiz.py"
    answers      = ["python quiz.py", "python -m quiz"]
    alternatives = ["python quiz", "python -m quiz.py"]
    hint         = "One option uses the filename, and the other uses the module name."

    [[python.questions]]
    question     = "What's the name of the list-like data structure in TOML"
    answers      = ["Array"]
    alternatives = ["List", "Sequence", "Set"]

    [[python.questions]]
    question = "What's a PEP"
    answers = ["A Python Enhancement Proposal"]
    alternatives = [
        "A Pretty Exciting Policy",
        "A Preciously Evolved Python",
        "A Potentially Epic Prize",
    ]
    hint = "PEPs are used to evolve Python."
    explanation = """
    Python Enhancement Proposals (PEPs) are design documents that provide
    information to the Python community. PEPs are used to propose new features
    for the Python language, to collect community input on an issue, and to
    document design decisions made about the language.
    """

    [[python.questions]]
    question = "How can you add a docstring to a function"
    answers = [
        "By writing a string literal as the first statement in the function",
        "By assigning a string to the function's .__doc__ attribute",
    ]
    alternatives = [
        "By using the built-in @docstring decorator",
        "By returning a string from the function",
    ]
    hint = "They are parsed from your code and stored on the function object."
    explanation = """
    Docstrings document functions and other Python objects. A docstring is a
    string literal that occurs as the first statement in a module, function,
    class, or method definition. Such a docstring becomes the .__doc__ special
    attribute of that object. See PEP 257 for more information.
    There's no built-in @docstring decorator. Many functions naturally return
    strings. Such a feature can therefore not be used for docstrings.
    """

    [[python.questions]]
    question = "When was the first public version of Python released"
    answers = ["February 1991"]
    alternatives = ["January 1994", "October 2000", "December 2008"]
    hint = "The first public version was labeled version 0.9.0."
    explanation = """
    Guido van Rossum started work on Python in December 1989. He posted
    Python v0.9.0 to the alt.sources newsgroup in February 1991. Python
    reached version 1.0.0 in January 1994. The next major versions,
    Python 2.0 and Python 3.0, were released in October 2000 and December
    2008, respectively.
    """
