[[questions]]
question = "When does __name__ == '__main__' equal True in a Python file"
answer = "When the file is run as a script"
alternatives = ["When the file is imported as a module", "When the file has a valid name", "When the file only has one function"]

[[questions]]
question = "Which three of the following address ranges are private?"
answer = ["172.16.0.0/12", "10.0.0.0/8", "192.168.0.0/16"]
alternatives = ["1.1.1.0/30", "127.0.0.0/24", "169.254.0.0/16", "193.168.255.0/24"]

[[questions]]
question = "What's the name of the list-like data structure in TOML"
answer = "Array"
alternatives = ["List", "Sequence", "Set"]

[[questions]]
question = "Which version of Python is the first with TOML support built in"
answer = "3.11"
alternatives = ["3.9", "3.10", "3.12"]
